default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "ag_pulido") %>
  password: <%= ENV["PGPASSWORD"] if ENV["PGPASSWORD"].present? %>

development:
  <<: *default
  database: ror_bookstore_development

test:
  <<: *default
  database: ror_bookstore_test

production:
  primary: &primary_production
    <<: *default
    database: ror_bookstore_production
    username: ror_bookstore
    password: <%= ENV["ROR_BOOKSTORE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: ror_bookstore_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ror_bookstore_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ror_bookstore_production_cable
    migrations_paths: db/cable_migrate
